#!/usr/bin/env bash
#
# test_e2e_noninteractive_node.sh — SPEC-001 TEST-2.1 `test-e2e-noninteractive-node`.
# Traceability: AC-SPEC-003 (noninteractive single-command), AC-SPEC-008
# (.github-project.json canonical schema), AC-SPEC-007 (skills copy), and the
# issue #8 known-edge-case from #5 (exec-bit invariant).
#
set -euo pipefail

source "$(dirname "$0")/lib/test_helpers.sh"

REPO_ROOT="$(e2e_repo_root "$0")"
INIT="$(e2e_init_script "$REPO_ROOT")"

e2e_begin "test-e2e-noninteractive-node"

TMP="$(e2e_make_fixture_repo "$(e2e_fixtures_dir "$REPO_ROOT")/repo-node-npm")"
trap 'rm -rf "$TMP"' EXIT

OUT="$TMP/stdout.log"; ERR="$TMP/stderr.log"
set +e
bash "$INIT" \
  --noninteractive \
  --project-dir "$TMP" \
  --worktree-root "$TMP/wt" \
  --name node-demo \
  --description "Node demo service" \
  --repo-role service \
  --github-owner antpolis \
  --github-project-number 9 \
  >"$OUT" 2>"$ERR"
RC=$?
set -e

assert_exit_zero "noninteractive init exit code" "$RC"

# AC-SPEC-003: no prompts surfaced in noninteractive mode.
if grep -q '\[prompt\]' "$OUT"; then
  check FAIL "noninteractive must not prompt"
else
  check OK "noninteractive: no prompts surfaced"
fi

# AC-SPEC-008: AGENTS.md created with generation comment (AC-SPEC-012).
assert_exists "AGENTS.md" "$TMP/AGENTS.md"
assert_file_contains "AGENTS.md generation comment" "$TMP/AGENTS.md" 'Generated by init-project v'

# Detected stack must be reflected in AGENTS.md (FR-2.2 / FR-5.3 traceable claim).
assert_file_contains "AGENTS.md reflects Node/npm detection" "$TMP/AGENTS.md" '[Nn]ode'
assert_file_contains "AGENTS.md reflects npm detection" "$TMP/AGENTS.md" 'npm'

# AC-SPEC-008: .github-project.json valid JSON with worktreeRoot + identity.
assert_exists ".github-project.json" "$TMP/.github-project.json"
assert_file_contains "worktreeRoot present" "$TMP/.github-project.json" '"worktreeRoot"'
assert_file_contains "identity.name matches --name" "$TMP/.github-project.json" '"node-demo"'
if node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$TMP/.github-project.json" >/dev/null 2>&1; then
  check OK ".github-project.json is valid JSON"
else
  check FAIL ".github-project.json is not valid JSON"
fi

# .opencode config gets the worktree external_directory entry (ARCH-003 Artifact 4).
OC_JSON="$TMP/.opencode/opencode.json"
if [[ -f "$OC_JSON" ]] && grep -q "$TMP/wt" "$OC_JSON"; then
  check OK "opencode config has worktree permission"
else
  check FAIL "opencode config missing worktree permission ($OC_JSON)"
fi

# AC-SPEC-007: exactly 3 skills + required scripts present.
assert_eq "exactly 3 skills" "$(e2e_count_skill_dirs "$TMP")" "3"
assert_exec "$TMP/.opencode/skills/github-issues-projects-cli/scripts/gh_project_helper.sh"
assert_exec "$TMP/.opencode/skills/do-task/scripts/create_task_worktree.sh"
assert_exec "$TMP/.opencode/skills/do-task/scripts/cleanup_task_worktree.sh"
assert_exec "$TMP/.opencode/skills/project-initialization/scripts/init_project_docs.sh"
assert_exec "$TMP/.opencode/skills/project-initialization/scripts/setup_project_docs.sh"

assert_file_contains "structured summary line" "$OUT" '\[summary\] Initialization complete'

e2e_done
