#!/usr/bin/env bash
#
# test_e2e_legacy_migrate.sh — SPEC-001 TEST-2.1 `test-e2e-legacy-migrate` +
# TEST-3.1. Traceability: AC-T7-005 ← AC-SPEC-004 (backward-compatible on
# legacy-initialized repo) + AC-SPEC-011 (migration does not delete legacy
# agent.md) + FR-6.1 (--migrate-agent-md).
#
# Fixture `repo-legacy-init` ships with: lowercase agent.md, a legacy
# .github-project.json (no worktreeRoot/identity/boundaries/initMeta), and a
# legacy .opencode/opencode.json. Running the upgraded init with
# --migrate-agent-md must: preserve agent.md verbatim, create AGENTS.md
# alongside it, and extend .github-project.json without dropping legacy fields.
#
set -euo pipefail

source "$(dirname "$0")/lib/test_helpers.sh"

REPO_ROOT="$(e2e_repo_root "$0")"
INIT="$(e2e_init_script "$REPO_ROOT")"

e2e_begin "test-e2e-legacy-migrate"

TMP="$(e2e_make_fixture_repo "$(e2e_fixtures_dir "$REPO_ROOT")/repo-legacy-init")"
trap 'rm -rf "$TMP"' EXIT

# Snapshot legacy agent.md content + .github-project.json before init so we can
# prove byte-identical preservation.
AGENT_MD_BEFORE=$(md5sum "$TMP/agent.md" | cut -d' ' -f1)
GH_BEFORE=$(cat "$TMP/.github-project.json")

OUT="$TMP/stdout.log"; ERR="$TMP/stderr.log"
set +e
bash "$INIT" \
  --noninteractive \
  --migrate-agent-md \
  --project-dir "$TMP" \
  --worktree-root "$TMP/wt" \
  --name legacy-demo \
  --description "Legacy migration demo" \
  --repo-role service \
  --github-owner antpolis \
  --github-project-number 9 \
  >"$OUT" 2>"$ERR"
RC=$?
set -e

assert_exit_zero "legacy migrate exit code" "$RC"

# AC-SPEC-011: legacy agent.md NEVER deleted.
assert_exists "legacy agent.md preserved" "$TMP/agent.md"
AGENT_MD_AFTER=$(md5sum "$TMP/agent.md" | cut -d' ' -f1)
assert_eq "agent.md byte-identical (not modified)" "$AGENT_MD_BEFORE" "$AGENT_MD_AFTER"

# AC-T7-005 / AC-SPEC-004: AGENTS.md created alongside agent.md (coexistence).
assert_exists "AGENTS.md created" "$TMP/AGENTS.md"
assert_file_contains "AGENTS.md generation comment" "$TMP/AGENTS.md" 'Generated by init-project v'

# AC-T7-005 / TEST-3.1: legacy .github-project.json fields survive the upgrade.
GH_AFTER=$(cat "$TMP/.github-project.json")
assert_file_contains "legacy owner preserved"        "$TMP/.github-project.json" '"owner": "antpolis"'
assert_file_contains "legacy owner_type preserved"   "$TMP/.github-project.json" '"owner_type": "org"'
assert_file_contains "legacy repo preserved"         "$TMP/.github-project.json" '"antpolis/legacy-demo"'
assert_file_contains "legacy project.number kept"    "$TMP/.github-project.json" '"number": 1'
assert_file_contains "legacy fields.status kept"     "$TMP/.github-project.json" '"PVTSSF_LEGACY"'
assert_file_contains "legacy status_options.todo"    "$TMP/.github-project.json" '"f75ad846"'

# New DM-1 fields added (AC-SPEC-004 bullet 3).
assert_file_contains "worktreeRoot added"            "$TMP/.github-project.json" '"worktreeRoot"'
assert_file_contains "identity added"                "$TMP/.github-project.json" '"identity"'
assert_file_contains "boundaries added"              "$TMP/.github-project.json" '"boundaries"'
assert_file_contains "initMeta added"                "$TMP/.github-project.json" '"initMeta"'

# .github-project.json remains valid JSON after the additive merge.
if node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$TMP/.github-project.json" >/dev/null 2>&1; then
  check OK ".github-project.json valid JSON after migrate"
else
  check FAIL ".github-project.json invalid JSON after migrate"
fi

# Skills copied on legacy repo (FR-7 still applies).
assert_eq "exactly 3 skills" "$(e2e_count_skill_dirs "$TMP")" "3"

e2e_done
