#!/usr/bin/env bash
#
# test_e2e_interactive_bare.sh — SPEC-001 TEST-2.1 `test-e2e-interactive-bare`.
# Traceability: AC-T7-002 ← AC-SPEC-002 (interactive mode completes with zero
# manual file editing) + AC-SPEC-007 (required skills copied) + AC-SPEC-012
# (AGENTS.md generation timestamp present).
#
# Approach: `init_project_docs.sh --interactive` forces interactive mode
# regardless of TTY, and `safe_read` reads piped stdin lines (tolerant of EOF).
# We feed 6 blank prompt responses (accept all detected defaults) plus a final
# "y" confirmation. This is the portable, dependency-free path allowed by
# TEST-2.2 — no `expect`/Tcl and no Node pseudo-TTY wrapper required.
#
set -euo pipefail

source "$(dirname "$0")/lib/test_helpers.sh"

REPO_ROOT="$(e2e_repo_root "$0")"
INIT="$(e2e_init_script "$REPO_ROOT")"

e2e_begin "test-e2e-interactive-bare"

TMP="$(e2e_make_fixture_repo "$(e2e_fixtures_dir "$REPO_ROOT")/repo-bare")"
trap 'rm -rf "$TMP"' EXIT

# GitHub owner/project-number are needed because the interactive defaults for a
# bare fixture cannot infer them; pass via flags so the blank prompts land on
# real defaults. 6 prompts (Q1..Q6) + 1 confirmation = 7 lines.
ANSWERS="$(printf '\n\n\n\n\n\ny\n')"

OUT="$TMP/stdout.log"; ERR="$TMP/stderr.log"
# Run from a CWD that is NOT the target so relative-path side effects are
# isolated. --interactive forces the mode; piped stdin drives safe_read.
set +e
echo "$ANSWERS" | bash "$INIT" \
  --interactive \
  --project-dir "$TMP" \
  --worktree-root "$TMP/wt" \
  --github-owner antpolis \
  --github-project-number 9 \
  >"$OUT" 2>"$ERR"
RC=$?
set -e

assert_exit_zero "interactive init exit code" "$RC"

# AC-T7-002: AGENTS.md exists with generation timestamp on line 1 (DM-2.1).
assert_exists "AGENTS.md" "$TMP/AGENTS.md"
assert_file_contains "AGENTS.md generation comment (DM-2.1 / AC-SPEC-012)" \
  "$TMP/AGENTS.md" 'Generated by init-project v'

# AC-T7-002: .github-project.json exists with worktreeRoot (AC-SPEC-008).
assert_exists ".github-project.json" "$TMP/.github-project.json"
assert_file_contains ".github-project.json has worktreeRoot" \
  "$TMP/.github-project.json" '"worktreeRoot"'
# Valid JSON (AC-SPEC-008: parseable by jq). Use node since jq is not guaranteed.
if node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$TMP/.github-project.json" >/dev/null 2>&1; then
  check OK ".github-project.json is valid JSON"
else
  check FAIL ".github-project.json is not valid JSON"
fi

# AC-T7-002 / AC-SPEC-007: exactly 3 required skills copied, no extras.
assert_eq "exactly 3 skills copied" "$(e2e_count_skill_dirs "$TMP")" "3"
assert_eq "github-issues-projects-cli present" "$(e2e_has_skill_dir "$TMP" github-issues-projects-cli)" "yes"
assert_eq "do-task present" "$(e2e_has_skill_dir "$TMP" do-task)" "yes"
assert_eq "project-initialization present" "$(e2e_has_skill_dir "$TMP" project-initialization)" "yes"
# Forbidden skills absent (ARCH-003 Artifact 3 guarantee 2).
assert_not_exists "skill-creator not copied" "$TMP/.opencode/skills/skill-creator"
assert_not_exists "webapp-testing not copied" "$TMP/.opencode/skills/webapp-testing"

# Known edge case from #5 (issue #8 collaboration record): fresh init on a
# clean repo with fixed source must produce every required script at mode 755.
assert_exec "$TMP/.opencode/skills/github-issues-projects-cli/scripts/gh_project_helper.sh"
assert_exec "$TMP/.opencode/skills/do-task/scripts/create_task_worktree.sh"
assert_exec "$TMP/.opencode/skills/do-task/scripts/cleanup_task_worktree.sh"
assert_exec "$TMP/.opencode/skills/project-initialization/scripts/init_project_docs.sh"
assert_exec "$TMP/.opencode/skills/project-initialization/scripts/setup_project_docs.sh"

# Interactive preview + write path must have surfaced the confirmation prompt
# and the final structured summary (OBS-1).
assert_file_contains "interactive prompt surfaced" "$OUT" '\[prompt\]'
assert_file_contains "AGENTS.md write logged" "$OUT" 'AGENTS.md'
assert_file_contains "structured summary line" "$OUT" '\[summary\] Initialization complete'

e2e_done
