#!/usr/bin/env bash
#
# tests/test_validate_agents_md.sh — SPEC-001-T8 unit tests.
#
# Migrated from tests/test_validate_agents_md.js (SPEC-004-T4, issue #54).
# Assertion parity: all 34 Node checks migrated 1:1; none weakened.
#
# Drives `templates/scripts/validate-agents-md.sh` (a pure bash script) against
# crafted AGENTS.md inputs and asserts the DM-2 / AC-T8 contract from issue #9
# + ARCH-003 + SPEC-001 TEST-4:
#
#   - AC-T8-001: known-good AGENTS.md exits 0 with all checks passing.
#   - AC-T8-002: missing generation timestamp on line 1 → [FAIL] + exit 1.
#   - AC-T8-003: empty H2 section → [FAIL] + exit 1.
#   - AC-T8-004: placeholder text → [FAIL] + exit 1.
#   - AC-T8-005: missing '## Local Configuration Files' → [FAIL] + exit 1.
#   - AC-T8-006: path listed in LCF that does not exist → [FAIL] + exit 1;
#                directory entries (trailing /) are accepted as well as files.
#   - DM-2.2:    H1 and H3+ headings → [FAIL] + exit 1.
#   - DM-2.2/DM-2.3 "valid hand-edits" guardrail: reordered sections and
#                operator-tweaked generation comment do NOT trigger failures.
#   - Usage:     missing arg / --help / nonexistent file → exit 2.
#
# Run directly: `bash tests/test_validate_agents_md.sh`.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/init_helpers.sh"

VALIDATOR="$INIT_REPO_ROOT/templates/scripts/validate-agents-md.sh"
NODE_FIXTURE="$INIT_REPO_ROOT/tests/fixtures/repo-node-npm"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

OUT="$TMP/out.txt"
ERR="$TMP/err.txt"

# Canonical known-good generation comment (format the generator emits per
# DM-2.1 / AC-SPEC-012; the validator accepts any well-shaped header).
GOOD_HEADER='<!-- Generated by init-project v0.3.0 on 2026-07-21T05:29:36.616Z — edit freely -->'

# run_validator ARGS... — run the validator from the repo root; the validator
# resolves repo-root from the AGENTS.md argument's parent dir, so CWD does not
# matter for the assertions.
run_validator() {
  init_run_cmd "$OUT" "$ERR" "$INIT_REPO_ROOT" -- bash "$VALIDATOR" "$@"
}

# make_project_dir NAME CONTENT — write CONTENT to <dir>/AGENTS.md and echo
# the dir (validator resolves paths relative to that parent dir).
make_project_dir() {
  local name="$1" content="$2"
  local dir="$TMP/$name"
  mkdir -p "$dir"
  printf '%s\n' "$content" > "$dir/AGENTS.md"
  printf '%s' "$dir"
}

# good_agents_md [EXTRA_LINES...] — canonical known-good document.
good_agents_md() {
  cat <<EOF
$GOOD_HEADER

## Repository Identity

Demo project
Role: service

## Stack

Language: Node.js

## Local Configuration Files

- \`AGENTS.md\` — canonical agent guidance for this repository
- \`.github-project.env\` — ANT_TEAM_* runtime exports (sole project config source)
- \`.opencode/skills/do-task/\` — task worktree management scripts
$*
EOF
}

# materialize_good_artifacts DIR — create the files the known-good fixture
# claims exist (AC-T8-006 happy path).
materialize_good_artifacts() {
  local dir="$1"
  printf "export ANT_TEAM_GITHUB_OWNER='o'\n" > "$dir/.github-project.env"
  mkdir -p "$dir/.opencode/skills/do-task"
}

# --- AC-T8-001: known-good AGENTS.md passes ------------------------------------

init_suite "AC-T8-001 known-good passes"

dir="$(make_project_dir ac001 "$(good_agents_md)")"
materialize_good_artifacts "$dir"
run_validator "$dir/AGENTS.md"
assert_exit_zero "AC-T8-001: known-good AGENTS.md exits 0" "$INIT_RC"
assert_out_contains "$OUT" '\[PASS\] DM-2\.1' "AC-T8-001: DM-2.1 [PASS] present"
assert_out_contains "$OUT" '\[PASS\] DM-2\.2' "AC-T8-001: DM-2.2 [PASS] present"
assert_out_contains "$OUT" '\[PASS\] DM-2\.3' "AC-T8-001: DM-2.3 [PASS] present"
assert_out_contains "$OUT" '\[PASS\] DM-2\.4' "AC-T8-001: DM-2.4 [PASS] present"
assert_out_contains "$OUT" '\[PASS\] AC-T8-006' "AC-T8-001: AC-T8-006 [PASS] present"
assert_out_contains "$OUT" '\[PASS\] AC-T8-004' "AC-T8-001: AC-T8-004 [PASS] present"
assert_out_contains "$OUT" '0 failed' "AC-T8-001: summary reports 0 failed"

dir="$(make_project_dir ac001-shape "$(good_agents_md)")"
materialize_good_artifacts "$dir"
run_validator "$dir/AGENTS.md"
assert_exit_zero "AC-T8-001 (shape): known-good exits 0" "$INIT_RC"
assert_out_contains "$OUT" '^Summary: [0-9]+ passed, 0 failed \([0-9]+ total\)$' \
  "AC-T8-001: summary line shape"
if grep -qF '[PASS]' "$ERR"; then
  check FAIL "AC-T8-001: [PASS] leaked to stderr"
else
  check OK "AC-T8-001: no [PASS] on stderr"
fi

# Real generator output regression: init the node-npm fixture, then validate.
init_suite "AC-T8-001 real generator output (regression)"

real_dir="$TMP/validate-real"
cp -R "$NODE_FIXTURE/." "$real_dir/" 2>/dev/null || { mkdir -p "$real_dir"; cp -R "$NODE_FIXTURE/." "$real_dir/"; }
mkdir -p "$real_dir/.git"
init_run "$OUT" "$ERR" -- \
  --noninteractive --project-dir "$real_dir" --worktree-root "$real_dir/wt" \
  --name demo-node-app --github-owner TestOrg --github-project-number 1 \
  --description "Demo Node app" --repo-role service
assert_exit_zero "AC-T8-001 (real): init exits 0" "$INIT_RC"
assert_exists "AC-T8-001 (real): init produced AGENTS.md" "$real_dir/AGENTS.md"
run_validator "$real_dir/AGENTS.md"
assert_exit_zero "AC-T8-001 (real): validator passes on real generator output" "$INIT_RC"

# --- AC-T8-002: missing generation timestamp on line 1 --------------------------

init_suite "AC-T8-002 missing generation timestamp"

dir="$(make_project_dir ac002-h1 '# Not the generation comment

## Local Configuration Files

- `AGENTS.md` — desc
')"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-002 (H1): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.1' "AC-T8-002 (H1): [FAIL] DM-2.1 on stderr"
assert_out_contains "$ERR" 'line 1 must be' "AC-T8-002 (H1): message explains line-1 contract"

dir="$(make_project_dir ac002-cmt '<!-- some other comment -->

## Local Configuration Files

- `AGENTS.md` — desc
')"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-002 (comment): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.1' "AC-T8-002 (comment): [FAIL] DM-2.1"

dir="$(make_project_dir ac002-noon '<!-- Generated by init-project v0.3.0 -->

## Local Configuration Files

- `AGENTS.md` — desc
')"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-002 (no ' on '): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.1' "AC-T8-002 (no ' on '): [FAIL] DM-2.1"

dir="$(make_project_dir ac002-edit '<!-- Generated by init-project v9.9.9-custom on 2030-01-01T00:00:00Z by operator -->

## Local Configuration Files

- `AGENTS.md` — desc
')"
run_validator "$dir/AGENTS.md"
if grep -qF '[FAIL] DM-2.1' "$ERR"; then
  check FAIL "AC-T8-002 (hand-edited): DM-2.1 should not flag well-shaped hand-edited header"
else
  check OK "AC-T8-002 (hand-edited): well-shaped hand-edited header not flagged"
fi

# --- AC-T8-003: empty H2 section -------------------------------------------------

init_suite "AC-T8-003 empty H2 section"

dir="$(make_project_dir ac003-empty "$GOOD_HEADER

## Stack

## Local Configuration Files

- \`AGENTS.md\` — desc
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-003 (empty): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.3' "AC-T8-003 (empty): [FAIL] DM-2.3 on stderr"
assert_out_contains "$ERR" 'AGENTS\.md:3' "AC-T8-003 (empty): reports file:line"

dir="$(make_project_dir ac003-eof "$GOOD_HEADER

## Stack


")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-003 (EOF): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.3' "AC-T8-003 (EOF): [FAIL] DM-2.3"

dir="$(make_project_dir ac003-ws "$GOOD_HEADER

## Stack

   
	

## Local Configuration Files

- \`AGENTS.md\` — desc
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-003 (whitespace): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.3' "AC-T8-003 (whitespace): whitespace-only body counts as empty"

# --- AC-T8-004: placeholder text --------------------------------------------------

init_suite "AC-T8-004 placeholder text"

for tc in 'TODO:Language: TODO' 'todo:Language: todo' 'fill:fill this in' 'ypn:your-project-name is a service' 'tbd:Language: TBD'; do
  key="${tc%%:*}"
  phrase="${tc#*:}"
  if [[ "$key" == "ypn" ]]; then
    body="$GOOD_HEADER

## Repository Identity

$phrase

## Local Configuration Files

- \`AGENTS.md\` — desc"
  else
    body="$GOOD_HEADER

## Stack

$phrase

## Local Configuration Files

- \`AGENTS.md\` — desc"
  fi
  dir="$(make_project_dir "ac004-$key" "$body")"
  run_validator "$dir/AGENTS.md"
  assert_exit_nonzero "AC-T8-004 ($phrase): exits non-zero" "$INIT_RC"
  assert_out_contains "$ERR" '\[FAIL\] AC-T8-004' "AC-T8-004 ($phrase): [FAIL] on stderr"
  assert_out_contains "$ERR" 'AGENTS\.md:[0-9]+' "AC-T8-004 ($phrase): reports file:line"
  if [[ "$key" == "TODO" ]]; then
    assert_out_contains "$ERR" 'TODO' "AC-T8-004: message names the offending pattern"
  fi
done

# --- AC-T8-005: missing LCF section ------------------------------------------------

init_suite "AC-T8-005 missing LCF section"

dir="$(make_project_dir ac005-none "$GOOD_HEADER

## Stack

Language: Node.js
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-005 (none): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.4' "AC-T8-005 (none): [FAIL] DM-2.4"
assert_out_contains "$ERR" 'Local Configuration Files' "AC-T8-005 (none): names the missing section"

dir="$(make_project_dir ac005-h3 "$GOOD_HEADER

## Stack

Language: Node.js

### Local Configuration Files

- \`AGENTS.md\` — desc
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-005 (H3): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.4' "AC-T8-005 (H3): DM-2.4 fails on H3 LCF"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.2' "AC-T8-005 (H3): DM-2.2 flags the H3"

# --- AC-T8-006: path existence ------------------------------------------------------

init_suite "AC-T8-006 path existence"

dir="$(make_project_dir ac006-missing "$GOOD_HEADER

## Local Configuration Files

- \`does-not-exist.json\` — bogus claim
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-006 (missing): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] AC-T8-006' "AC-T8-006 (missing): [FAIL] on stderr"
assert_out_contains "$ERR" 'does-not-exist\.json' "AC-T8-006 (missing): names the missing path"

dir="$(make_project_dir ac006-dir "$GOOD_HEADER

## Local Configuration Files

- \`config/\` — config dir
")"
mkdir -p "$dir/config"
run_validator "$dir/AGENTS.md"
assert_exit_zero "AC-T8-006 (dir): directory entry passes" "$INIT_RC"
assert_out_contains "$OUT" '\[PASS\] AC-T8-006: path exists: config/' "AC-T8-006 (dir): PASS names the directory"

dir="$(make_project_dir ac006-nodir "$GOOD_HEADER

## Local Configuration Files

- \`missing-dir/\` — bogus
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-006 (no dir): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] AC-T8-006' "AC-T8-006 (no dir): [FAIL] on stderr"

dir="$(make_project_dir ac006-rel "$GOOD_HEADER

## Local Configuration Files

- \`local.txt\` — desc
")"
printf 'ok\n' > "$dir/local.txt"
run_validator "$dir/AGENTS.md"
assert_exit_zero "AC-T8-006 (relative): paths resolve relative to AGENTS.md parent" "$INIT_RC"

dir="$(make_project_dir ac006-mixed "$GOOD_HEADER

## Local Configuration Files

- \`present.txt\` — desc
- \`absent.txt\` — desc
")"
printf 'ok\n' > "$dir/present.txt"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "AC-T8-006 (mixed): overall exit non-zero when any path missing" "$INIT_RC"
assert_out_contains "$OUT" '\[PASS\] AC-T8-006: path exists: present\.txt' "AC-T8-006 (mixed): present path PASSes"
assert_out_contains "$ERR" '\[FAIL\] AC-T8-006: path does not exist: absent\.txt' "AC-T8-006 (mixed): absent path FAILs"

# --- DM-2.2: H1 / H3+ heading detection ----------------------------------------------

init_suite "DM-2.2 H1 / H3 detection"

dir="$(make_project_dir dm222-h1 "$GOOD_HEADER

# Top-level Title

## Local Configuration Files

- \`AGENTS.md\` — desc
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "DM-2.2 (H1): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.2' "DM-2.2 (H1): [FAIL] on stderr"
assert_out_contains "$ERR" 'AGENTS\.md:3' "DM-2.2 (H1): reports the offending line"

dir="$(make_project_dir dm222-h3 "$GOOD_HEADER

## Stack

Language: Node.js

### Subsection

More text

## Local Configuration Files

- \`AGENTS.md\` — desc
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "DM-2.2 (H3): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.2' "DM-2.2 (H3): [FAIL] on stderr"
assert_out_contains "$ERR" '### Subsection' "DM-2.2 (H3): names the offending heading"

dir="$(make_project_dir dm222-h4 "$GOOD_HEADER

## Stack

Language: Node.js

#### Deep

Text

## Local Configuration Files

- \`AGENTS.md\` — desc
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "DM-2.2 (H4): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\] DM-2\.2' "DM-2.2 (H4): [FAIL] on stderr"

# --- Hand-edit guardrail ----------------------------------------------------------------

init_suite "hand-edit guardrail"

dir="$(make_project_dir hand-order "$GOOD_HEADER

## Local Configuration Files

- \`AGENTS.md\` — desc

## Stack

Language: Node.js
")"
run_validator "$dir/AGENTS.md"
assert_exit_zero "hand-edit: reordered sections still pass" "$INIT_RC"

dir="$(make_project_dir hand-extra "$(good_agents_md '

## Deployment Notes

Deploy on merge to main.')")"
materialize_good_artifacts "$dir"
run_validator "$dir/AGENTS.md"
assert_exit_zero "hand-edit: extra non-standard H2 section with real body still passes" "$INIT_RC"

# --- Usage / argument errors --------------------------------------------------------------

init_suite "usage / arg errors"

run_validator
assert_eq "usage: no args → exit 2" "$INIT_RC" "2"
assert_out_contains "$ERR" 'Usage:' "usage: no args prints usage to stderr"

run_validator --help
assert_eq "usage: --help → exit 2" "$INIT_RC" "2"
assert_out_contains "$ERR" 'Usage:' "usage: --help prints usage to stderr"

run_validator -h
assert_eq "usage: -h → exit 2" "$INIT_RC" "2"
assert_out_contains "$ERR" 'Usage:' "usage: -h prints usage to stderr"

bogus="$TMP/validate-amd-nope-$$.md"
rm -f "$bogus"
run_validator "$bogus"
assert_eq "usage: nonexistent file → exit 2" "$INIT_RC" "2"
assert_out_contains "$ERR" '\[error\] File not found' "usage: nonexistent file reports [error] File not found"
assert_out_contains "$ERR" "$bogus" "usage: error message names the missing file path"

run_validator a.md b.md
assert_eq "usage: too many args → exit 2" "$INIT_RC" "2"
assert_out_contains "$ERR" 'Usage:' "usage: too many args prints usage to stderr"

# --- Exit-code + reporting semantics ----------------------------------------------------------

init_suite "exit-code semantics"

dir="$(make_project_dir shape "$(good_agents_md)")"
materialize_good_artifacts "$dir"
run_validator "$dir/AGENTS.md"
assert_exit_zero "reporting: known-good exits 0" "$INIT_RC"
pass_lines="$(grep -cF '[PASS]' "$OUT" || true)"
assert_eq "reporting: exactly 8 [PASS] lines for the 3-path fixture" "$pass_lines" "8"
if grep -qF '[FAIL]' "$OUT" || grep -qF '[FAIL]' "$ERR"; then
  check FAIL "reporting: no [FAIL] expected on known-good"
else
  check OK "reporting: no [FAIL] on known-good"
fi

dir="$(make_project_dir shape-fail "$GOOD_HEADER

## Stack

## Local Configuration Files

- \`missing.txt\` — desc
")"
run_validator "$dir/AGENTS.md"
assert_exit_nonzero "reporting (fail case): exits non-zero" "$INIT_RC"
assert_out_contains "$ERR" '\[FAIL\]' "reporting (fail case): [FAIL] on stderr"
if grep -qF '[FAIL]' "$OUT"; then
  check FAIL "reporting (fail case): [FAIL] must not leak to stdout"
else
  check OK "reporting (fail case): no [FAIL] on stdout"
fi
assert_out_contains "$OUT" 'Summary:' "reporting (fail case): summary still on stdout"

# --- Summary -------------------------------------------------------------------------------------

init_done
