#!/usr/bin/env node
'use strict';

/*
 * tests/test_validate_agents_md.js — SPEC-001-T8 unit tests.
 *
 * Drives `scripts/validate-agents-md.sh` against crafted AGENTS.md inputs
 * and asserts the DM-2 / AC-T8 contract from issue #9 + ARCH-003 + SPEC-001
 * TEST-4:
 *
 *   - AC-T8-001: known-good AGENTS.md exits 0 with all checks passing.
 *   - AC-T8-002: missing generation timestamp on line 1 → [FAIL] + exit 1.
 *   - AC-T8-003: empty H2 section → [FAIL] + exit 1.
 *   - AC-T8-004: placeholder text → [FAIL] + exit 1.
 *   - AC-T8-005: missing '## Local Configuration Files' → [FAIL] + exit 1.
 *   - AC-T8-006: path listed in LCF that does not exist → [FAIL] + exit 1;
 *                directory entries (trailing /) are accepted as well as files.
 *   - DM-2.2:    H1 and H3+ headings → [FAIL] + exit 1.
 *   - DM-2.2/DM-2.3 "valid hand-edits" guardrail: reordered sections and
 *                operator-tweaked generation comment do NOT trigger failures.
 *   - Usage:     missing arg / --help / nonexistent file → exit 2.
 *
 * The validator is a pure bash script (no Node dependency in the script
 * itself). The test harness uses Node only for assertion machinery, matching
 * the pattern in tests/test_skills_copy.js and tests/test_agents_md_gen.js.
 *
 * No external npm dependencies — Node built-ins only.
 */

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const assert = require('assert');

const REPO_ROOT = path.resolve(__dirname, '..');
const VALIDATOR = path.join(REPO_ROOT, 'scripts', 'validate-agents-md.sh');

let pass = 0;
let fail = 0;
const failures = [];

function check(name, fn) {
  try {
    fn();
    pass++;
  } catch (err) {
    fail++;
    failures.push({ name, message: err.message, stack: err.stack });
    process.stdout.write(`  FAIL: ${name}\n    ${err.message}\n`);
  }
}

// Run the validator with given argv. Returns {stdout, stderr, status}.
function runValidator(argv) {
  const result = { stdout: '', stderr: '', status: 0 };
  try {
    result.stdout = execFileSync('bash', [VALIDATOR, ...argv], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      // The validator's repo-root resolution uses `cd` into the parent dir
      // of the AGENTS.md argument, so working directory does not matter.
      cwd: REPO_ROOT,
      timeout: 15000,
    });
  } catch (err) {
    result.status = err.status ?? 1;
    result.stdout = err.stdout ? err.stdout.toString('utf8') : '';
    result.stderr = err.stderr ? err.stderr.toString('utf8') : '';
  }
  return result;
}

// Write `content` to a fresh AGENTS.md inside a temp repo-rooted directory
// and return that directory's path. The validator resolves repo-root as the
// parent dir of the AGENTS.md argument, so files placed in this directory
// are visible to the AC-T8-006 existence check.
function makeProjectDir(prefix, content) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), `validate-amd-${prefix}-`));
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), content);
  return dir;
}

// Canonical known-good generation comment. Mirrors the format the
// init-project generator emits per DM-2.1 / AC-SPEC-012.
const GOOD_HEADER =
  '<!-- Generated by init-project v0.3.0 on 2026-07-21T05:29:36.616Z — edit freely -->';

// Canonical known-good AGENTS.md. Includes all sections the generator is
// allowed to emit (DM-2.2 standard set), has non-empty bodies (DM-2.3),
// has the LCF section (DM-2.4), lists only files that the test setup will
// create on disk (AC-T8-006), and contains no placeholder text (AC-T8-004).
function goodAgentsMd(extra) {
  const lines = [
    GOOD_HEADER,
    '',
    '## Repository Identity',
    '',
    'Demo project',
    'Role: service',
    '',
    '## Stack',
    '',
    'Language: Node.js',
    '',
    '## Local Configuration Files',
    '',
    '- `AGENTS.md` — canonical agent guidance for this repository',
    '- `.github-project.json` — GitHub workflow metadata',
    '- `.opencode/skills/project-initialization/` — re-initialization scripts',
  ];
  if (extra) lines.push(...extra);
  return lines.join('\n') + '\n';
}

// Files the known-good fixture claims exist (AC-T8-006 happy path).
function materializeGoodArtifacts(dir) {
  fs.writeFileSync(path.join(dir, '.github-project.json'), '{}\n');
  fs.mkdirSync(path.join(dir, '.opencode', 'skills', 'project-initialization'), {
    recursive: true,
  });
}

// ===========================================================================
// AC-T8-001: known-good AGENTS.md passes
// ===========================================================================

process.stdout.write('Suite: AC-T8-001 known-good passes\n');

check('AC-T8-001: known-good AGENTS.md exits 0 with all checks passing', () => {
  const dir = makeProjectDir('ac001', goodAgentsMd());
  materializeGoodArtifacts(dir);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0, `exit ${r.status}\nstdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  // Every check contributes one or more [PASS] lines; the four structural
  // checks (DM-2.1/2.2/2.3/2.4) and AC-T8-004 must each appear. AC-T8-006
  // emits one [PASS] per listed path (3 entries → 3 [PASS] lines).
  assert.ok(/\[PASS\] DM-2\.1/.test(r.stdout), 'DM-2.1 [PASS] missing');
  assert.ok(/\[PASS\] DM-2\.2/.test(r.stdout), 'DM-2.2 [PASS] missing');
  assert.ok(/\[PASS\] DM-2\.3/.test(r.stdout), 'DM-2.3 [PASS] missing');
  assert.ok(/\[PASS\] DM-2\.4/.test(r.stdout), 'DM-2.4 [PASS] missing');
  assert.ok(/\[PASS\] AC-T8-006/.test(r.stdout), 'AC-T8-006 [PASS] missing');
  assert.ok(/\[PASS\] AC-T8-004/.test(r.stdout), 'AC-T8-004 [PASS] missing');
  assert.ok(/0 failed/.test(r.stdout), `summary should report 0 failed:\n${r.stdout}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-001: every [PASS] line and final summary appears on stdout', () => {
  const dir = makeProjectDir('ac001-shape', goodAgentsMd());
  materializeGoodArtifacts(dir);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0, `exit ${r.status}\nstderr:\n${r.stderr}`);
  // Summary line shape — used by CI / operators to confirm the verdict.
  assert.ok(/^Summary: \d+ passed, 0 failed \(\d+ total\)$/m.test(r.stdout),
    `summary line shape wrong:\n${r.stdout}`);
  // All [PASS] lines go to stdout (not stderr).
  assert.ok(!/\[PASS\]/.test(r.stderr), `[PASS] leaked to stderr:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-001: validator passes on real generator output (regression)', () => {
  // Generate a real AGENTS.md from the init-project generator against the
  // node-npm fixture and validate it. This proves the validator agrees with
  // the generator on every section the generator actually emits.
  const initScript = path.join(
    REPO_ROOT,
    '.opencode/skills/project-initialization/scripts/init_project_docs.sh'
  );
  const fixtureSrc = path.join(REPO_ROOT, 'tests', 'fixtures', 'repo-node-npm');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'validate-amd-real-'));
  // Copy fixture into tmp (excluding .git which can't be tracked nested).
  for (const entry of fs.readdirSync(fixtureSrc, { withFileTypes: true })) {
    fs.cpSync(path.join(fixtureSrc, entry.name), path.join(tmp, entry.name), {
      recursive: true,
    });
  }
  fs.mkdirSync(path.join(tmp, '.git'), { recursive: true });
  const initRes = execFileSync(
    'bash',
    [
      initScript,
      '--noninteractive',
      '--project-dir', tmp,
      '--worktree-root', path.join(tmp, 'wt'),
      '--name', 'demo-node-app',
      '--github-owner', 'TestOrg',
      '--github-project-number', '1',
      '--description', 'Demo Node app',
      '--repo-role', 'service',
    ],
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 30000 }
  );
  // Sanity: the init script must have written AGENTS.md.
  assert.ok(fs.existsSync(path.join(tmp, 'AGENTS.md')),
    `init did not produce AGENTS.md\nstdout:\n${initRes}`);
  // All artifacts the generator lists in LCF should be present on disk after
  // a real init — so the validator should pass.
  const r = runValidator([path.join(tmp, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0,
    `validator should pass on real generator output\nstdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  fs.rmSync(tmp, { recursive: true, force: true });
});

// ===========================================================================
// AC-T8-002: missing generation timestamp on line 1
// ===========================================================================

process.stdout.write('Suite: AC-T8-002 missing generation timestamp\n');

check('AC-T8-002: missing timestamp (random H1 line) → [FAIL] DM-2.1 + exit 1', () => {
  const dir = makeProjectDir('ac002-h1', '# Not the generation comment\n\n## Local Configuration Files\n\n- `AGENTS.md` — desc\n');
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1, `expected exit 1, got ${r.status}\nstdout:\n${r.stdout}`);
  assert.ok(/\[FAIL\] DM-2\.1/.test(r.stderr), 'DM-2.1 [FAIL] missing from stderr');
  assert.ok(/line 1 must be/.test(r.stderr), 'DM-2.1 message should explain line 1 contract');
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-002: plain comment without "Generated by init-project v" → [FAIL] DM-2.1', () => {
  const dir = makeProjectDir('ac002-cmt', '<!-- some other comment -->\n\n## Local Configuration Files\n\n- `AGENTS.md` — desc\n');
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1, `expected exit 1, got ${r.status}\nstdout:\n${r.stdout}`);
  assert.ok(/\[FAIL\] DM-2\.1/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-002: missing " on " separator → [FAIL] DM-2.1', () => {
  // Has "Generated by init-project v..." but no " on " → invalid per DM-2.1.
  const dir = makeProjectDir('ac002-noon', '<!-- Generated by init-project v0.3.0 -->\n\n## Local Configuration Files\n\n- `AGENTS.md` — desc\n');
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1, `expected exit 1, got ${r.status}\nstdout:\n${r.stdout}`);
  assert.ok(/\[FAIL\] DM-2\.1/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-002: hand-edited version + timestamp still pass (no false positive)', () => {
  // Operators may legitimately edit the version string or timestamp text.
  const handEditedHeader = '<!-- Generated by init-project v9.9.9-custom on 2030-01-01T00:00:00Z by operator -->';
  const dir = makeProjectDir('ac002-edit', `${handEditedHeader}\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  // DM-2.1 must NOT flag a hand-edited but well-shaped header.
  assert.ok(!/\[FAIL\] DM-2\.1/.test(r.stderr),
    `DM-2.1 should not flag well-shaped hand-edited header:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// AC-T8-003: empty H2 section
// ===========================================================================

process.stdout.write('Suite: AC-T8-003 empty H2 section\n');

check('AC-T8-003: H2 heading immediately followed by next H2 → [FAIL] DM-2.3', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac003-empty', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1, `expected exit 1, got ${r.status}\nstdout:\n${r.stdout}`);
  assert.ok(/\[FAIL\] DM-2\.3/.test(r.stderr), 'DM-2.3 [FAIL] missing from stderr');
  // The offending line number should be reported with file:line info.
  assert.ok(/AGENTS\.md:3/.test(r.stderr),
    `DM-2.3 should report file:line for the empty heading:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-003: H2 heading followed only by blank lines then EOF → [FAIL] DM-2.3', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\n\n`;
  const dir = makeProjectDir('ac003-eof', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] DM-2\.3/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-003: H2 with whitespace-only body still counts as empty', () => {
  // Whitespace-only lines do not constitute body content per DM-2.3.
  const body = `${GOOD_HEADER}\n\n## Stack\n\n   \n\t\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac003-ws', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] DM-2\.3/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// AC-T8-004: placeholder text
// ===========================================================================

process.stdout.write('Suite: AC-T8-004 placeholder text\n');

check('AC-T8-004: "TODO" → [FAIL] with file:line', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nLanguage: TODO\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac004-todo', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] AC-T8-004/.test(r.stderr), 'AC-T8-004 [FAIL] missing');
  assert.ok(/TODO/.test(r.stderr), 'message should name the offending pattern');
  assert.ok(/AGENTS\.md:\d+/.test(r.stderr),
    `AC-T8-004 should report file:line:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-004: case-insensitive "todo" → [FAIL]', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nLanguage: todo\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac004-lower', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] AC-T8-004/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-004: "fill this in" → [FAIL]', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nfill this in\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac004-fill', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] AC-T8-004/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-004: "your-project-name" → [FAIL]', () => {
  const body = `${GOOD_HEADER}\n\n## Repository Identity\n\nyour-project-name is a service\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac004-ypn', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] AC-T8-004/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-004: "TBD" → [FAIL]', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nLanguage: TBD\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac004-tbd', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] AC-T8-004/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// AC-T8-005: missing '## Local Configuration Files' section
// ===========================================================================

process.stdout.write('Suite: AC-T8-005 missing LCF section\n');

check('AC-T8-005: no LCF section at all → [FAIL] DM-2.4 + exit 1', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nLanguage: Node.js\n`;
  const dir = makeProjectDir('ac005-none', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] DM-2\.4/.test(r.stderr),
    `DM-2.4 [FAIL] missing:\n${r.stderr}`);
  assert.ok(/Local Configuration Files/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-005: LCF as H3 (not H2) → [FAIL] DM-2.4 (and DM-2.2)', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nLanguage: Node.js\n\n### Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('ac005-h3', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  // DM-2.4 requires the H2 form; an H3-form LCF does not satisfy the contract.
  assert.ok(/\[FAIL\] DM-2\.4/.test(r.stderr), 'DM-2.4 should fail on H3 LCF');
  // DM-2.2 should also flag the H3.
  assert.ok(/\[FAIL\] DM-2\.2/.test(r.stderr), 'DM-2.2 should flag the H3');
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// AC-T8-006: file/path existence check
// ===========================================================================

process.stdout.write('Suite: AC-T8-006 path existence\n');

check('AC-T8-006: file listed in LCF does not exist → [FAIL] + exit 1', () => {
  const dir = makeProjectDir('ac006-missing',
    `${GOOD_HEADER}\n\n## Local Configuration Files\n\n- \`does-not-exist.json\` — bogus claim\n`);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] AC-T8-006/.test(r.stderr));
  assert.ok(/does-not-exist\.json/.test(r.stderr),
    'message should name the missing path');
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-006: directory entry with trailing slash resolves correctly', () => {
  // The generator emits directories with trailing slashes; the validator
  // must accept them as existence-check subjects.
  const dir = makeProjectDir('ac006-dir',
    `${GOOD_HEADER}\n\n## Local Configuration Files\n\n- \`config/\` — config dir\n`);
  fs.mkdirSync(path.join(dir, 'config'));
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0,
    `directory entry should pass existence check\nstdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.ok(/\[PASS\] AC-T8-006: path exists: config\//.test(r.stdout));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-006: directory entry with trailing slash that does NOT exist → [FAIL]', () => {
  const dir = makeProjectDir('ac006-nodir',
    `${GOOD_HEADER}\n\n## Local Configuration Files\n\n- \`missing-dir/\` — bogus\n`);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] AC-T8-006/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-006: paths resolve relative to the AGENTS.md parent dir, not CWD', () => {
  // Place AGENTS.md in a temp dir with a real file; run validator from
  // REPO_ROOT. The validator must resolve the path relative to the AGENTS.md
  // location, not the current working directory.
  const dir = makeProjectDir('ac006-rel',
    `${GOOD_HEADER}\n\n## Local Configuration Files\n\n- \`local.txt\` — desc\n`);
  fs.writeFileSync(path.join(dir, 'local.txt'), 'ok\n');
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0,
    `path resolution should be relative to AGENTS.md parent\nstderr:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

check('AC-T8-006: multiple paths, one missing → only that one FAILs', () => {
  // Per-check granularity: existing paths emit [PASS], missing emit [FAIL].
  const dir = makeProjectDir('ac006-mixed',
    `${GOOD_HEADER}\n\n## Local Configuration Files\n\n- \`present.txt\` — desc\n- \`absent.txt\` — desc\n`);
  fs.writeFileSync(path.join(dir, 'present.txt'), 'ok\n');
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1, 'overall exit must be 1 if any path missing');
  assert.ok(/\[PASS\] AC-T8-006: path exists: present\.txt/.test(r.stdout),
    `present path should be reported as PASS:\n${r.stdout}`);
  assert.ok(/\[FAIL\] AC-T8-006: path does not exist: absent\.txt/.test(r.stderr),
    `absent path should be reported as FAIL:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// DM-2.2: H1 / H3+ heading detection
// ===========================================================================

process.stdout.write('Suite: DM-2.2 H1 / H3 detection\n');

check('DM-2.2: H1 heading → [FAIL] DM-2.2 with file:line', () => {
  const body = `${GOOD_HEADER}\n\n# Top-level Title\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('dm222-h1', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] DM-2\.2/.test(r.stderr));
  assert.ok(/AGENTS\.md:3/.test(r.stderr),
    `DM-2.2 should report the offending line:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

check('DM-2.2: H3 heading → [FAIL] DM-2.2', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nLanguage: Node.js\n\n### Subsection\n\nMore text\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('dm222-h3', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] DM-2\.2/.test(r.stderr));
  assert.ok(/### Subsection/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('DM-2.2: H4 heading → [FAIL] DM-2.2', () => {
  const body = `${GOOD_HEADER}\n\n## Stack\n\nLanguage: Node.js\n\n#### Deep\n\nText\n\n## Local Configuration Files\n\n- \`AGENTS.md\` — desc\n`;
  const dir = makeProjectDir('dm222-h4', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  assert.ok(/\[FAIL\] DM-2\.2/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// Hand-edit guardrail: benign hand-edits must NOT fail
// ===========================================================================

process.stdout.write('Suite: hand-edit guardrail\n');

check('hand-edit: sections in non-standard order still pass', () => {
  // The issue guardrail explicitly says: don't require exact heading order.
  const body = [
    GOOD_HEADER,
    '',
    '## Local Configuration Files',
    '',
    '- `AGENTS.md` — desc',
    '',
    '## Stack',
    '',
    'Language: Node.js',
    '',
  ].join('\n') + '\n';
  const dir = makeProjectDir('hand-order', body);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0,
    `reordered sections should pass\nstdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

check('hand-edit: extra non-standard H2 section with real body still passes', () => {
  // DM-2.2 lists the *standard set* of possible headings — operators adding
  // project-specific H2 sections (e.g. "## Deployment Notes") is a valid
  // hand-edit per the guardrail.
  const body = goodAgentsMd([
    '',
    '## Deployment Notes',
    '',
    'Deploy on merge to main.',
  ]);
  const dir = makeProjectDir('hand-extra', body);
  materializeGoodArtifacts(dir);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0,
    `extra H2 section should pass\nstdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// Usage / argument errors
// ===========================================================================

process.stdout.write('Suite: usage / arg errors\n');

check('usage: no args → exit 2 + usage to stderr', () => {
  const r = runValidator([]);
  assert.strictEqual(r.status, 2, `expected exit 2, got ${r.status}`);
  assert.ok(/Usage:/.test(r.stderr), `usage text missing:\n${r.stderr}`);
});

check('usage: --help → exit 2 + usage to stderr', () => {
  const r = runValidator(['--help']);
  assert.strictEqual(r.status, 2);
  assert.ok(/Usage:/.test(r.stderr));
});

check('usage: -h → exit 2 + usage to stderr', () => {
  const r = runValidator(['-h']);
  assert.strictEqual(r.status, 2);
  assert.ok(/Usage:/.test(r.stderr));
});

check('usage: nonexistent file → exit 2 with "[error] File not found"', () => {
  const bogus = path.join(os.tmpdir(), `validate-amd-nope-${process.pid}.md`);
  // Ensure the path does not exist.
  fs.rmSync(bogus, { force: true });
  const r = runValidator([bogus]);
  assert.strictEqual(r.status, 2);
  assert.ok(/\[error\] File not found/.test(r.stderr),
    `expected [error] File not found:\n${r.stderr}`);
  assert.ok(bogus.includes(r.stderr.split('File not found:')[1]?.trim() || ''),
    'error message should name the missing file path');
});

check('usage: too many args → exit 2', () => {
  const r = runValidator(['a.md', 'b.md']);
  assert.strictEqual(r.status, 2);
  assert.ok(/Usage:/.test(r.stderr));
});

// ===========================================================================
// Exit-code + reporting semantics
// ===========================================================================

process.stdout.write('Suite: exit-code semantics\n');

check('reporting: every check emits exactly one verdict prefix ([PASS] or [FAIL])', () => {
  // For AC-T8-006 the validator emits one line per listed path. The four
  // structural checks (DM-2.1..2.4) and AC-T8-004 each emit exactly one line.
  const dir = makeProjectDir('shape', goodAgentsMd());
  materializeGoodArtifacts(dir);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 0);
  // Count verdict lines exactly.
  const passLines = (r.stdout.match(/\[PASS\]/g) || []).length;
  // 4 structural (DM-2.1/2.2/2.3/2.4) + AC-T8-004 + 3 AC-T8-006 (one per listed path) = 8.
  assert.strictEqual(passLines, 8,
    `expected 8 [PASS] lines for the 3-path fixture, got ${passLines}\n${r.stdout}`);
  // No [FAIL] lines should be emitted.
  assert.ok(!/\[FAIL\]/.test(r.stdout) && !/\[FAIL\]/.test(r.stderr));
  fs.rmSync(dir, { recursive: true, force: true });
});

check('reporting: failures go to stderr, passes go to stdout', () => {
  // Verify the convention stated in the script header: PASS → stdout,
  // FAIL → stderr. This lets CI capture them separately.
  const dir = makeProjectDir('shape-fail',
    `${GOOD_HEADER}\n\n## Stack\n\n## Local Configuration Files\n\n- \`missing.txt\` — desc\n`);
  const r = runValidator([path.join(dir, 'AGENTS.md')]);
  assert.strictEqual(r.status, 1);
  // All [FAIL] content must be on stderr.
  assert.ok(/\[FAIL\]/.test(r.stderr), '[FAIL] should be on stderr');
  assert.ok(!/\[FAIL\]/.test(r.stdout), '[FAIL] must not leak to stdout');
  // Summary should still be on stdout (informational final line).
  assert.ok(/Summary:/.test(r.stdout), 'summary should be on stdout');
  fs.rmSync(dir, { recursive: true, force: true });
});

// ===========================================================================
// Entry point
// ===========================================================================

function main() {
  process.stdout.write(`\n${pass} passed, ${fail} failed\n`);
  if (fail > 0) {
    process.stderr.write('\nFailures:\n');
    for (const f of failures) {
      process.stderr.write(`  - ${f.name}: ${f.message}\n`);
    }
    process.exit(1);
  }
  process.exit(0);
}

main();
