#!/usr/bin/env bash
#
# validate-agents-md.sh — structural validator for AGENTS.md (ARCH-003 DM-2).
#
# Checks the structural rules from ARCH-003 DM-2 / SPEC-001 TEST-4.2:
#
#   DM-2.1  line 1 is the generation timestamp HTML comment
#   DM-2.2  sections use H2 headings only (reject H1 and H3+)
#   DM-2.3  no empty H2 section (heading with no body before next heading / EOF)
#   DM-2.4  `## Local Configuration Files` section is present
#   AC-T8-006  every path listed in `## Local Configuration Files` exists
#   AC-T8-004  no placeholder text (TODO, fill this in, your-project-name, TBD)
#
# Usage:
#   scripts/validate-agents-md.sh <path-to-agents.md>
#
# Output: one `[PASS]` / `[FAIL]` line per check to stdout / stderr, then a
# final `Summary: N passed, M failed` line. Exit codes:
#   0  all checks passed
#   1  at least one check failed
#   2  usage error or input file missing
#
# Pure bash + grep + sed + awk only (no Node.js dependency, per issue #9
# tech-lead guardrails). Designed to validate any AGENTS.md that follows
# the DM-2 contract, not just files produced by init-project.
#
# Repo root for the file-existence check (AC-T8-006) is resolved as the
# parent directory of the AGENTS.md argument. Paths in the `## Local
# Configuration Files` section are listed relative to that root.

set -euo pipefail

pass_count=0
fail_count=0

pass() {
  echo "[PASS] $1"
  pass_count=$((pass_count + 1))
}

fail() {
  echo "[FAIL] $1" >&2
  fail_count=$((fail_count + 1))
}

usage() {
  cat <<'USAGE'
Usage:
  scripts/validate-agents-md.sh <path-to-agents.md>

Checks the DM-2 structural contract for AGENTS.md:
  - Line 1 is the generation timestamp HTML comment (DM-2.1)
  - Sections use H2 headings only (DM-2.2)
  - No empty H2 sections (DM-2.3)
  - `## Local Configuration Files` section is present (DM-2.4)
  - Every path listed in Local Configuration Files exists on disk (AC-T8-006)
  - No placeholder text: TODO, fill this in, your-project-name, TBD (AC-T8-004)

Exit codes:
  0  all checks passed
  1  at least one check failed
  2  usage error or input file missing

Examples:
  scripts/validate-agents-md.sh AGENTS.md
  scripts/validate-agents-md.sh /tmp/broken-agents.md
USAGE
}

# --- Arg + input validation --------------------------------------------------

if [[ $# -ne 1 || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage >&2
  exit 2
fi

agents_file="$1"

if [[ ! -f "$agents_file" ]]; then
  echo "[error] File not found: $agents_file" >&2
  exit 2
fi

# Repo root = parent directory of the AGENTS.md file. Paths inside the
# `## Local Configuration Files` section are interpreted relative to this.
repo_root="$(cd "$(dirname "$agents_file")" && pwd)"

# --- DM-2.1: line 1 is the generation timestamp HTML comment -----------------
#
# ARCH-003 DM-2.1 / SPEC-001 AC-SPEC-012 require:
#   <!-- Generated by init-project vX.Y.Z on <ISO 8601> — edit freely -->
#
# The check is permissive on the parts operators may legitimately hand-edit
# (version, exact timestamp text, trailing prose) but strict on the parts the
# contract guarantees (HTML comment, "Generated by init-project v", " on "
# separating version from timestamp). This satisfies the guardrail: "AGENTS.md
# may have been hand-edited after generation — script must not fail on valid
# hand-edits."

line1="$(head -n 1 "$agents_file")"
if printf '%s' "$line1" | grep -Eq '^<!-- Generated by init-project v[^>]+ on [^>]+-->$'; then
  pass "DM-2.1: line 1 is the generation timestamp comment"
else
  fail "DM-2.1: line 1 must be '<!-- Generated by init-project vX.Y.Z on <ISO> ... -->' (got: $line1)"
fi

# --- DM-2.2: sections use H2 headings only -----------------------------------
#
# DM-2.2: sections must use H2 (`##`). ATX H1 (`# `) and H3+ (`###`) are
# violations. The generator never emits them; a hand-edit adding one breaks
# the section grammar that downstream agents and validators assume.
#
# Detection runs over every line. A line counts as an offending heading if it
# starts with `# ` (H1) or `###` (H3 or deeper). Lines starting with `## `
# are valid and excluded by both regexes.

non_h2_hits="$(grep -nE '^(# |###)' "$agents_file" || true)"
if [[ -z "$non_h2_hits" ]]; then
  pass "DM-2.2: no H1 or H3+ headings found (sections are H2-only)"
else
  # Report every offending line with file:line prefixes so the operator can
  # find and fix them. The bound is the file size, which is small for any
  # realistic AGENTS.md.
  fail "DM-2.2: found non-H2 ATX heading(s) (expected H2 only):"
  while IFS= read -r hit; do
    echo "         $agents_file:$hit" >&2
  done <<<"$non_h2_hits"
fi

# --- DM-2.3: no empty H2 sections --------------------------------------------
#
# DM-2.3: a section with no body content must be omitted. An "empty section"
# is a `## Heading` line whose body (lines until the next heading or EOF,
# excluding blank lines) contains no characters.
#
# The awk below walks the file once. `cur_ln` holds the line number of the
# currently-open H2 section (0 = no open section); `cur_title` is the heading
# text; `has_body` becomes 1 the moment a non-blank line lands inside the open
# section. `flush()` is invoked when the open section closes (next `## ` or
# any other heading or EOF) and records a failure if `has_body` is still 0.

empty_section_hits="$(awk '
  function flush() {
    if (cur_ln > 0 && !has_body) {
      print cur_ln ":## " cur_title
      bad = 1
    }
    cur_ln = 0
    cur_title = ""
    has_body = 0
  }
  /^## / {
    flush()
    cur_ln = NR
    cur_title = substr($0, 4)
    next
  }
  /^# / || /^###/ {
    flush()
    next
  }
  cur_ln > 0 {
    if ($0 ~ /[^ \t]/) has_body = 1
  }
  END {
    flush()
    exit (bad ? 1 : 0)
  }
' "$agents_file" || true)"
if [[ -z "$empty_section_hits" ]]; then
  pass "DM-2.3: no empty H2 sections found"
else
  fail "DM-2.3: found H2 section(s) with no body text:"
  while IFS= read -r hit; do
    line_no="${hit%%:*}"
    title="${hit#*:}"
    echo "         $agents_file:$line_no $title" >&2
  done <<<"$empty_section_hits"
fi

# --- DM-2.4: `## Local Configuration Files` section is present ---------------
#
# DM-2.4: the initializer must add a `## Local Configuration Files` section.
# It is the only section that is mandatory even when others are empty.

if grep -Eq '^## Local Configuration Files[[:space:]]*$' "$agents_file"; then
  pass "DM-2.4: '## Local Configuration Files' section is present"
else
  fail "DM-2.4: required '## Local Configuration Files' section is missing"
fi

# --- AC-T8-006: every path listed in Local Configuration Files exists --------
#
# DM-2.4 / AC-T8-006: every artifact claim in `## Local Configuration Files`
# must match the filesystem (no fabricated facts). The awk below scopes to
# the LCF section (from the `## Local Configuration Files` heading until the
# next `## ` heading or EOF) and emits the first backticked path on each
# `- \`...\`` list item line.
#
# The generator emits both files (`AGENTS.md`) and directories
# (`.opencode/skills/foo/`) in this section. The tech-lead guardrail suggested
# `[[ -f ]]`, but strict file-only checks would reject the directory entries
# that the generator is required to produce per ARCH-003 / DM-2.4. `[[ -e ]]`
# (entry exists) is the smallest primitive that honors the contract for both
# files and directories. Trailing slashes are stripped before resolution.

lcf_paths="$(awk '
  BEGIN { in_lcf = 0 }
  /^## / {
    in_lcf = ($0 ~ /^## Local Configuration Files[[:space:]]*$/) ? 1 : 0
    next
  }
  !in_lcf { next }
  # Match list-item lines of the form: "- `path` ..." (path is the first
  # backticked segment after the list marker).
  {
    if ($0 !~ /^- `/) next
    rest = substr($0, 4)        # strip "- `"
    end = index(rest, "`")      # find closing backtick
    if (end <= 0) next
    print substr(rest, 1, end - 1)
  }
' "$agents_file" || true)"

if [[ -z "$lcf_paths" ]]; then
  # Note: the message is left generic ("no list items found") rather than
  # claiming the section is missing — the dedicated DM-2.4 check above owns
  # the "section absent" failure mode. AC-T8-006 only fires when the section
  # is present but lists zero backticked path entries (e.g. an operator added
  # prose-only content), or as a co-symptom when DM-2.4 already failed.
  fail "AC-T8-006: no backticked path list items found in '## Local Configuration Files'"
else
  while IFS= read -r raw_path; do
    [[ -n "$raw_path" ]] || continue
    cleaned="${raw_path%/}"   # tolerate directory entries with trailing slash
    target="$repo_root/$cleaned"
    if [[ -e "$target" ]]; then
      pass "AC-T8-006: path exists: $raw_path"
    else
      fail "AC-T8-006: path does not exist: $raw_path (resolved: $target)"
    fi
  done <<<"$lcf_paths"
fi

# --- AC-T8-004: no placeholder text ------------------------------------------
#
# AC-SPEC-006 / TEST-4.1 / AC-T8-004: AGENTS.md must not contain placeholder
# text. The patterns are the exact strings named in the issue body and
# TEST-4.1: "TODO", "fill this in", "your-project-name", "TBD". Match is
# case-insensitive so "todo", "Todo", and "TODO" are all caught.

placeholder_hits="$(grep -niE 'TODO|fill this in|your-project-name|TBD' "$agents_file" || true)"
if [[ -z "$placeholder_hits" ]]; then
  pass "AC-T8-004: no placeholder text (TODO / fill this in / your-project-name / TBD)"
else
  fail "AC-T8-004: placeholder text found:"
  while IFS= read -r hit; do
    echo "         $agents_file:$hit" >&2
  done <<<"$placeholder_hits"
fi

# --- Summary -----------------------------------------------------------------

total=$((pass_count + fail_count))
echo ""
echo "Summary: $pass_count passed, $fail_count failed ($total total)"

if (( fail_count > 0 )); then
  exit 1
fi
exit 0
